#### Exercício 1
Apresentar o quadrado dos números inteiros de 15 a 200

In [1]:
for i in range(15, 201):
    quadrado = i ** 2
    print(f"O quadrado de {i} é {quadrado}")

O quadrado de 15 é 225
O quadrado de 16 é 256
O quadrado de 17 é 289
O quadrado de 18 é 324
O quadrado de 19 é 361
O quadrado de 20 é 400
O quadrado de 21 é 441
O quadrado de 22 é 484
O quadrado de 23 é 529
O quadrado de 24 é 576
O quadrado de 25 é 625
O quadrado de 26 é 676
O quadrado de 27 é 729
O quadrado de 28 é 784
O quadrado de 29 é 841
O quadrado de 30 é 900
O quadrado de 31 é 961
O quadrado de 32 é 1024
O quadrado de 33 é 1089
O quadrado de 34 é 1156
O quadrado de 35 é 1225
O quadrado de 36 é 1296
O quadrado de 37 é 1369
O quadrado de 38 é 1444
O quadrado de 39 é 1521
O quadrado de 40 é 1600
O quadrado de 41 é 1681
O quadrado de 42 é 1764
O quadrado de 43 é 1849
O quadrado de 44 é 1936
O quadrado de 45 é 2025
O quadrado de 46 é 2116
O quadrado de 47 é 2209
O quadrado de 48 é 2304
O quadrado de 49 é 2401
O quadrado de 50 é 2500
O quadrado de 51 é 2601
O quadrado de 52 é 2704
O quadrado de 53 é 2809
O quadrado de 54 é 2916
O quadrado de 55 é 3025
O quadrado de 56 é 3136
O quadrado de 57 é 3249
O quadrado de 58 é 3364
O quadrado de 59 é 3481
O quadrado de 60 é 3600
O quadrado de 61 é 3721
O quadrado de 62 é 3844
O quadrado de 63 é 3969
O quadrado de 64 é 4096
O quadrado de 65 é 4225
O quadrado de 66 é 4356
O quadrado de 67 é 4489
O quadrado de 68 é 4624
O quadrado de 69 é 4761
O quadrado de 70 é 4900
O quadrado de 71 é 5041
O quadrado de 72 é 5184
O quadrado de 73 é 5329
O quadrado de 74 é 5476
O quadrado de 75 é 5625
O quadrado de 76 é 5776
O quadrado de 77 é 5929
O quadrado de 78 é 6084
O quadrado de 79 é 6241
O quadrado de 80 é 6400
O quadrado de 81 é 6561
O quadrado de 82 é 6724
O quadrado de 83 é 6889
O quadrado de 84 é 7056
O quadrado de 85 é 7225
O quadrado de 86 é 7396
O quadrado de 87 é 7569
O quadrado de 88 é 7744
O quadrado de 89 é 7921
O quadrado de 90 é 8100
O quadrado de 91 é 8281
O quadrado de 92 é 8464
O quadrado de 93 é 8649
O quadrado de 94 é 8836
O quadrado de 95 é 9025
O quadrado de 96 é 9216
O quadrado de 97 é 9409
O quadrado de 98 é 9604
O quadrado de 99 é 9801
O quadrado de 100 é 10000
O quadrado de 101 é 10201
O quadrado de 102 é 10404
O quadrado de 103 é 10609
O quadrado de 104 é 10816
O quadrado de 105 é 11025
O quadrado de 106 é 11236
O quadrado de 107 é 11449
O quadrado de 108 é 11664
O quadrado de 109 é 11881
O quadrado de 110 é 12100
O quadrado de 111 é 12321
O quadrado de 112 é 12544
O quadrado de 113 é 12769
O quadrado de 114 é 12996
O quadrado de 115 é 13225
O quadrado de 116 é 13456
O quadrado de 117 é 13689
O quadrado de 118 é 13924
O quadrado de 119 é 14161
O quadrado de 120 é 14400
O quadrado de 121 é 14641
O quadrado de 122 é 14884
O quadrado de 123 é 15129
O quadrado de 124 é 15376
O quadrado de 125 é 15625
O quadrado de 126 é 15876
O quadrado de 127 é 16129
O quadrado de 128 é 16384
O quadrado de 129 é 16641
O quadrado de 130 é 16900
O quadrado de 131 é 17161
O quadrado de 132 é 17424
O quadrado de 133 é 17689
O quadrado de 134 é 17956
O quadrado de 135 é 18225
O quadrado de 136 é 18496
O quadrado de 137 é 18769
O quadrado de 138 é 19044
O quadrado de 139 é 19321
O quadrado de 140 é 19600
O quadrado de 141 é 19881
O quadrado de 142 é 20164
O quadrado de 143 é 20449
O quadrado de 144 é 20736
O quadrado de 145 é 21025
O quadrado de 146 é 21316
O quadrado de 147 é 21609
O quadrado de 148 é 21904
O quadrado de 149 é 22201
O quadrado de 150 é 22500
O quadrado de 151 é 22801
O quadrado de 152 é 23104
O quadrado de 153 é 23409
O quadrado de 154 é 23716
O quadrado de 155 é 24025
O quadrado de 156 é 24336
O quadrado de 157 é 24649
O quadrado de 158 é 24964
O quadrado de 159 é 25281
O quadrado de 160 é 25600
O quadrado de 161 é 25921
O quadrado de 162 é 26244
O quadrado de 163 é 26569
O quadrado de 164 é 26896
O quadrado de 165 é 27225
O quadrado de 166 é 27556
O quadrado de 167 é 27889
O quadrado de 168 é 28224
O quadrado de 169 é 28561
O quadrado de 170 é 28900
O quadrado de 171 é 29241
O quadrado de 172 é 29584
O quadrado de 173 é 29929
O quadrado de 174 é 30276
O quadrado de 175 é 30625
O quadrado de 176 é 30976
O quadrado de 177 é 31329
O quadrado de 178 é 31684
O quadrado de 179 é 32041
O quadrado de 180 é 32400
O quadrado de 181 é 32761
O quadrado de 182 é 33124
O quadrado de 183 é 33489
O quadrado de 184 é 33856
O quadrado de 185 é 34225
O quadrado de 186 é 34596
O quadrado de 187 é 34969
O quadrado de 188 é 35344
O quadrado de 189 é 35721
O quadrado de 190 é 36100
O quadrado de 191 é 36481
O quadrado de 192 é 36864
O quadrado de 193 é 37249
O quadrado de 194 é 37636
O quadrado de 195 é 38025
O quadrado de 196 é 38416
O quadrado de 197 é 38809
O quadrado de 198 é 39204
O quadrado de 199 é 39601
O quadrado de 200 é 40000

#### Exercício 2

Apresentar o total da soma obtida dos cem primeiros números inteiros
(1+2+3+4+5+6+7+...+97+98+99+100)

In [3]:
soma = 0

for i in range(1, 101):
  soma += i

print(f"O total da soma dos cem primeiros números inteiros é: {soma}.")

O total da soma dos cem primeiros números inteiros é: 5050

#### Exercício 3
Escrever um algoritmo que lê 5 valores para a variável A, um de cada vez,
e contar quantos destes valores são negativos. Após a leitura, o programa deve mostrar
a quantidade de números negativos

In [5]:
negativos = 0

for i in range(5):
  valor = float(input(f"Digite o {i+1}º valor: "))
  if valor < 0:
    negativos += 1

print(f"A quantidade de números negativos é: {negativos}.")

Digite o 1º valor: 4
Digite o 2º valor: -9
Digite o 3º valor: 8
Digite o 4º valor: 10
Digite o 5º valor: -1
A quantidade de números negativos é: 2.

#### Exercício 4
Ler duas notas e informar a média. Se o valor digitado for menor do que 0 (zero)
ou maior do que 10 (dez), o usuário deve digitar a nota novamente

In [8]:
def ler_nota():
  while True:
    nota = float(input("Digite uma nota (entre 0 e 10): "))
    if 0 <= nota <= 10:
      return nota
    else:
      print("Por favor, digite uma nota válida entre 0 e 10.")

nota1 = ler_nota()
nota2 = ler_nota()

media = (nota1 + nota2) / 2

print(f"A média das notas informadas é: {media}.")

Digite uma nota (entre 0 e 10): 15
Por favor, digite uma nota válida entre 0 e 10.
Digite uma nota (entre 0 e 10): 12
Por favor, digite uma nota válida entre 0 e 10.
Digite uma nota (entre 0 e 10): 10
Digite uma nota (entre 0 e 10): 18
Por favor, digite uma nota válida entre 0 e 10.
Digite uma nota (entre 0 e 10): 5
A média das notas informadas é: 7.5.