<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **Aula 05 - Indexação e Seleção de Dados**

<br>
<br>

___

**Importação da Biblioteca**

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Arquivos/ideb.csv')

In [ ]:
df.head()

,ano,sigla_uf,id_municipio,rede,ensino,anos_escolares,taxa_aprovacao,indicador_rendimento,nota_saeb_matematica,nota_saeb_lingua_portuguesa,nota_saeb_media_padronizada,ideb,projecao
0,2011,PR,4110805,publica,fundamental,finais (6-9),73.6,0.732192,255.3,237.94,4.887500,3.6,3.8
1,2019,PA,1506906,municipal,fundamental,finais (6-9),93.1,0.931595,249.0,264.36,5.223000,4.9,5.2
2,2021,MS,5007307,estadual,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
3,2021,RN,2410009,municipal,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
4,2005,PR,4117305,publica,fundamental,finais (6-9),71.1,0.716839,239.1,223.19,4.372333,3.1,NaN

In [ ]:
df['rede']

0         publica
1       municipal
2        estadual
3       municipal
4         publica
          ...
9995      publica
9996     estadual
9997      publica
9998    municipal
9999      publica
Name: rede, Length: 10000, dtype: object

In [ ]:
df[['rede']]

           rede
0       publica
1     municipal
2      estadual
3     municipal
4       publica
...         ...
9995    publica
9996   estadual
9997    publica
9998  municipal
9999    publica

[10000 rows x 1 columns]

In [ ]:
df[['ano', 'rede']]

       ano       rede
0     2011    publica
1     2019  municipal
2     2021   estadual
3     2021  municipal
4     2005    publica
...    ...        ...
9995  2005    publica
9996  2015   estadual
9997  2009    publica
9998  2019  municipal
9999  2007    publica

[10000 rows x 2 columns]

In [ ]:
df['rede'][1]

'municipal'

In [ ]:
df['rede'][2:5]

2     estadual
3    municipal
4      publica
Name: rede, dtype: object

In [ ]:
df[['rede']][2:5]

        rede
2   estadual
3  municipal
4    publica

**loc[linhas, colunas]**: é o método de seleção de dados baseado em rótulo, o que significa que temos que passar o nome da coluna ou o número da linha que queremos selecionar.

In [ ]:
df.loc[:, :]

,ano,sigla_uf,id_municipio,rede,ensino,anos_escolares,taxa_aprovacao,indicador_rendimento,nota_saeb_matematica,nota_saeb_lingua_portuguesa,nota_saeb_media_padronizada,ideb,projecao
0,2011,PR,4110805,publica,fundamental,finais (6-9),73.6,0.732192,255.30,237.94,4.887500,3.6,3.8
1,2019,PA,1506906,municipal,fundamental,finais (6-9),93.1,0.931595,249.00,264.36,5.223000,4.9,5.2
2,2021,MS,5007307,estadual,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
3,2021,RN,2410009,municipal,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
4,2005,PR,4117305,publica,fundamental,finais (6-9),71.1,0.716839,239.10,223.19,4.372333,3.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,AM,1304062,publica,fundamental,finais (6-9),64.4,0.647776,228.50,216.50,4.082500,2.6,NaN
9996,2015,MG,3108305,estadual,fundamental,iniciais (1-5),100.0,1.000000,NaN,NaN,6.097130,6.1,6.4
9997,2009,MG,3105707,publica,fundamental,iniciais (1-5),88.9,0.892924,211.27,183.27,5.328105,4.8,4.6
9998,2019,RS,4318424,municipal,fundamental,iniciais (1-5),100.0,1.000000,236.88,226.94,6.611036,6.6,5.8
9999,2007,RS,4313201,publica,fundamental,iniciais (1-5),93.5,0.939828,217.00,194.44,5.640547,5.3,4.9

In [ ]:
df.loc[:, ['ano']]

       ano
0     2011
1     2019
2     2021
3     2021
4     2005
...    ...
9995  2005
9996  2015
9997  2009
9998  2019
9999  2007

[10000 rows x 1 columns]

In [ ]:
df.loc[:, ['ano', 'rede']]

       ano       rede
0     2011    publica
1     2019  municipal
2     2021   estadual
3     2021  municipal
4     2005    publica
...    ...        ...
9995  2005    publica
9996  2015   estadual
9997  2009    publica
9998  2019  municipal
9999  2007    publica

[10000 rows x 2 columns]

In [ ]:
df.loc[5, ['ano', 'rede']]

ano        2007
rede    publica
Name: 5, dtype: object

In [ ]:
df.loc[2:5]

,ano,sigla_uf,id_municipio,rede,ensino,anos_escolares,taxa_aprovacao,indicador_rendimento,nota_saeb_matematica,nota_saeb_lingua_portuguesa,nota_saeb_media_padronizada,ideb,projecao
2,2021,MS,5007307,estadual,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
3,2021,RN,2410009,municipal,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
4,2005,PR,4117305,publica,fundamental,finais (6-9),71.1,0.716839,239.10,223.19,4.372333,3.1,NaN
5,2007,SP,3544608,publica,fundamental,finais (6-9),89.8,0.895217,223.86,205.07,3.815667,3.4,3.7

In [ ]:
df.loc[[2]]

,ano,sigla_uf,id_municipio,rede,ensino,anos_escolares,taxa_aprovacao,indicador_rendimento,nota_saeb_matematica,nota_saeb_lingua_portuguesa,nota_saeb_media_padronizada,ideb,projecao
2,2021,MS,5007307,estadual,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8

In [ ]:
df.loc[2:5, ['ano', 'rede']]

    ano       rede
2  2021   estadual
3  2021  municipal
4  2005    publica
5  2007    publica

In [ ]:
df.loc[df['ano'] == 2011]

,ano,sigla_uf,id_municipio,rede,ensino,anos_escolares,taxa_aprovacao,indicador_rendimento,nota_saeb_matematica,nota_saeb_lingua_portuguesa,nota_saeb_media_padronizada,ideb,projecao
0,2011,PR,4110805,publica,fundamental,finais (6-9),73.6,0.732192,255.30,237.94,4.887500,3.6,3.8
8,2011,MA,2102077,publica,fundamental,iniciais (1-5),84.4,0.844759,172.66,158.77,4.146191,3.5,4.0
9,2011,PA,1503408,estadual,fundamental,finais (6-9),71.5,0.736057,218.64,213.75,3.873333,2.9,3.5
12,2011,MG,3103900,publica,fundamental,finais (6-9),79.9,0.792950,282.55,266.25,5.813500,4.6,4.3
17,2011,RS,4319711,estadual,fundamental,finais (6-9),85.0,0.847300,NaN,NaN,NaN,NaN,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,2011,PR,4116802,estadual,fundamental,finais (6-9),91.0,0.909790,236.74,218.36,4.251667,3.9,3.9
9942,2011,MG,3157278,publica,fundamental,finais (6-9),72.9,0.730422,295.04,273.00,6.134000,4.5,4.2
9956,2011,RS,4319208,estadual,fundamental,finais (6-9),84.8,0.854422,256.57,251.41,5.133167,4.4,4.1
9965,2011,PR,4121356,publica,fundamental,finais (6-9),92.0,0.922712,257.85,246.61,5.074500,4.7,3.3
9993,2011,PB,2512705,publica,fundamental,iniciais (1-5),83.4,0.832117,190.13,172.58,4.730488,3.9,3.3

In [ ]:
df.loc[(df['ano'] == 2011) & (df['rede'] == 'publica')]

,ano,sigla_uf,id_municipio,rede,ensino,anos_escolares,taxa_aprovacao,indicador_rendimento,nota_saeb_matematica,nota_saeb_lingua_portuguesa,nota_saeb_media_padronizada,ideb,projecao
0,2011,PR,4110805,publica,fundamental,finais (6-9),73.6,0.732192,255.30,237.94,4.887500,3.6,3.8
8,2011,MA,2102077,publica,fundamental,iniciais (1-5),84.4,0.844759,172.66,158.77,4.146191,3.5,4.0
12,2011,MG,3103900,publica,fundamental,finais (6-9),79.9,0.792950,282.55,266.25,5.813500,4.6,4.3
57,2011,GO,5203939,publica,fundamental,finais (6-9),88.0,0.877493,251.00,234.58,4.759833,4.2,4.1
101,2011,MS,5000203,publica,fundamental,finais (6-9),77.8,0.774715,251.80,240.08,4.865000,3.8,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9930,2011,GO,5207501,publica,fundamental,finais (6-9),84.7,0.845306,246.71,244.83,4.859000,4.1,3.9
9935,2011,TO,1720903,publica,fundamental,iniciais (1-5),86.5,0.874886,211.10,190.38,5.454133,4.8,3.9
9942,2011,MG,3157278,publica,fundamental,finais (6-9),72.9,0.730422,295.04,273.00,6.134000,4.5,4.2
9965,2011,PR,4121356,publica,fundamental,finais (6-9),92.0,0.922712,257.85,246.61,5.074500,4.7,3.3
9993,2011,PB,2512705,publica,fundamental,iniciais (1-5),83.4,0.832117,190.13,172.58,4.730488,3.9,3.3

In [ ]:
df.loc[(df['ano'] == 2011) | (df['rede'] == 'publica')]

,ano,sigla_uf,id_municipio,rede,ensino,anos_escolares,taxa_aprovacao,indicador_rendimento,nota_saeb_matematica,nota_saeb_lingua_portuguesa,nota_saeb_media_padronizada,ideb,projecao
0,2011,PR,4110805,publica,fundamental,finais (6-9),73.6,0.732192,255.30,237.94,4.887500,3.6,3.8
4,2005,PR,4117305,publica,fundamental,finais (6-9),71.1,0.716839,239.10,223.19,4.372333,3.1,NaN
5,2007,SP,3544608,publica,fundamental,finais (6-9),89.8,0.895217,223.86,205.07,3.815667,3.4,3.7
6,2021,RS,4315800,publica,fundamental,iniciais (1-5),NaN,NaN,NaN,NaN,NaN,NaN,6.4
8,2011,MA,2102077,publica,fundamental,iniciais (1-5),84.4,0.844759,172.66,158.77,4.146191,3.5,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9992,2021,PR,4121752,publica,medio,todos (1-4),NaN,NaN,NaN,NaN,NaN,NaN,3.8
9993,2011,PB,2512705,publica,fundamental,iniciais (1-5),83.4,0.832117,190.13,172.58,4.730488,3.9,3.3
9995,2005,AM,1304062,publica,fundamental,finais (6-9),64.4,0.647776,228.50,216.50,4.082500,2.6,NaN
9997,2009,MG,3105707,publica,fundamental,iniciais (1-5),88.9,0.892924,211.27,183.27,5.328105,4.8,4.6
9999,2007,RS,4313201,publica,fundamental,iniciais (1-5),93.5,0.939828,217.00,194.44,5.640547,5.3,4.9

In [ ]:
df.head()

,ano,sigla_uf,id_municipio,rede,ensino,anos_escolares,taxa_aprovacao,indicador_rendimento,nota_saeb_matematica,nota_saeb_lingua_portuguesa,nota_saeb_media_padronizada,ideb,projecao
0,2011,PR,4110805,publica,fundamental,finais (6-9),73.6,0.732192,255.3,237.94,4.887500,3.6,3.8
1,2019,PA,1506906,municipal,fundamental,finais (6-9),93.1,0.931595,249.0,264.36,5.223000,4.9,5.2
2,2021,MS,5007307,estadual,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
3,2021,RN,2410009,municipal,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
4,2005,PR,4117305,publica,fundamental,finais (6-9),71.1,0.716839,239.1,223.19,4.372333,3.1,NaN

In [ ]:
df.loc[0:5, ['ano']] = 2022

In [ ]:
df.head()

,ano,sigla_uf,id_municipio,rede,ensino,anos_escolares,taxa_aprovacao,indicador_rendimento,nota_saeb_matematica,nota_saeb_lingua_portuguesa,nota_saeb_media_padronizada,ideb,projecao
0,2022,PR,4110805,publica,fundamental,finais (6-9),73.6,0.732192,255.3,237.94,4.887500,3.6,3.8
1,2022,PA,1506906,municipal,fundamental,finais (6-9),93.1,0.931595,249.0,264.36,5.223000,4.9,5.2
2,2022,MS,5007307,estadual,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
3,2022,RN,2410009,municipal,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
4,2022,PR,4117305,publica,fundamental,finais (6-9),71.1,0.716839,239.1,223.19,4.372333,3.1,NaN

**iloc[linhas, colunas]**: é um método de seleção baseado em indexação, o que significa que temos que passar um índice inteiro no método para selecionar uma linha ou coluna específica.

In [ ]:
df.iloc[:, :]

,ano,sigla_uf,id_municipio,rede,ensino,anos_escolares,taxa_aprovacao,indicador_rendimento,nota_saeb_matematica,nota_saeb_lingua_portuguesa,nota_saeb_media_padronizada,ideb,projecao
0,2022,PR,4110805,publica,fundamental,finais (6-9),73.6,0.732192,255.30,237.94,4.887500,3.6,3.8
1,2022,PA,1506906,municipal,fundamental,finais (6-9),93.1,0.931595,249.00,264.36,5.223000,4.9,5.2
2,2022,MS,5007307,estadual,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
3,2022,RN,2410009,municipal,fundamental,finais (6-9),NaN,NaN,NaN,NaN,NaN,NaN,4.8
4,2022,PR,4117305,publica,fundamental,finais (6-9),71.1,0.716839,239.10,223.19,4.372333,3.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,AM,1304062,publica,fundamental,finais (6-9),64.4,0.647776,228.50,216.50,4.082500,2.6,NaN
9996,2015,MG,3108305,estadual,fundamental,iniciais (1-5),100.0,1.000000,NaN,NaN,6.097130,6.1,6.4
9997,2009,MG,3105707,publica,fundamental,iniciais (1-5),88.9,0.892924,211.27,183.27,5.328105,4.8,4.6
9998,2019,RS,4318424,municipal,fundamental,iniciais (1-5),100.0,1.000000,236.88,226.94,6.611036,6.6,5.8
9999,2007,RS,4313201,publica,fundamental,iniciais (1-5),93.5,0.939828,217.00,194.44,5.640547,5.3,4.9

In [ ]:
df.iloc[0:5, 0]

0    2022
1    2022
2    2022
3    2022
4    2022
Name: ano, dtype: int64