<div>
<p ><img  align="right" src="https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco,dpr_1/aj29iemt0ogdyrdlksd4" height="160px"></p>
</div>

<br>
<br>

# **Aula 07 - Combinando Dados**

<br>
<br>

___

**Importação da Biblioteca**

In [ ]:
import pandas as pd

A função **concat()** faz todo o trabalho pesado de realizar operações de concatenação ao longo de um eixo enquanto executa a lógica de conjunto opcional (união ou interseção) dos índices (se houver) nos outros eixos.


<img  align="left" src="https://pandas.pydata.org/docs/_images/merging_concat_basic.png">

In [ ]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)


df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },
    index=[4, 5, 6, 7],
)

In [ ]:
df1.head()

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df1.shape

(4, 4)

In [ ]:
df2.head()

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [ ]:
df2.shape

(4, 4)

In [ ]:
result = pd.concat([df1, df2])

result.head()

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4

In [ ]:
result.shape

(8, 4)

**Definir lógica dos eixos**

Ao combinar vários DataFrames, você tem a opção de como lidar com outros eixos (além do que está sendo concatenado). Isso pode ser feito das duas maneiras a seguir:

Leve a união de todos eles, join='outer'. Esta é a opção padrão, pois resulta em perda zero de informações.

<div>
<img  align="left" src="https://pandas.pydata.org/docs/_images/merging_concat_axis1.png">
</div>


Pegue o cruzamento, join='inner'.

<div>
<img  align="left" src="https://pandas.pydata.org/docs/_images/merging_concat_axis1_inner.png">
</div>

In [ ]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },
    index=[0, 1, 2, 3],
)

df4 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },
    index=[2, 3, 6, 7],
)

In [ ]:
df1.head()

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
df4.head()

    B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7

In [ ]:
result = pd.concat([df1, df4], axis=1, join='outer')

result

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [ ]:
result = pd.concat([df1, df4], axis=1, join="inner")

result

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3